# Generated by Django 4.2.13 on 2024-07-19 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivityPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(verbose_name='内容')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='re_activity_author', to=settings.AUTH_USER_MODEL, verbose_name='发布作者')),
                ('likes', models.ManyToManyField(related_name='re_activity_likes', to=settings.AUTH_USER_MODEL, verbose_name='点赞')),
            ],
            options={
                'verbose_name': '动态帖子',
            },
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(max_length=200, verbose_name='评论内容')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='re_activity_comment_author', to=settings.AUTH_USER_MODEL, verbose_name='评论发布者')),
                ('fatherComment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_activity_comment', to='api.activitycomment', verbose_name='父评论')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_activity_comment_activity', to='api.activitypost', verbose_name='所属的帖子')),
            ],
            options={
                'verbose_name': '动态的评论',
            },
        ),
    ]
