# Generated by Django 4.2.13 on 2024-07-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_avatar_user_activitypost_activitycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='test', max_length=15, verbose_name='昵称'),
            preserve_default=False,
        ),
    ]
