# Generated by Django 4.2.13 on 2024-08-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blogtag_alter_file_hash_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visible',
            field=models.BooleanField(default=1, verbose_name='可见性'),
            preserve_default=False,
        ),
    ]
