# Generated by Django 4.2.13 on 2024-08-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_blog_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('last_heartrate', models.FloatField()),
                ('last_updated_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='activitycomment',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
